# Generated by Django 5.2.6 on 2025-09-09 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_year'],
                'unique_together': {('start_year', 'end_year')},
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='perf.domain')),
            ],
        ),
        migrations.CreateModel(
            name='GrowthPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_statement', models.TextField()),
                ('indicators_of_success', models.TextField()),
                ('actions', models.TextField()),
                ('timelines', models.CharField(max_length=150)),
                ('resources', models.TextField(blank=True, null=True)),
                ('evaluator_name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.academicyear')),
                ('components_addressed', models.ManyToManyField(related_name='growth_plans', to='perf.component')),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hod_comment', models.TextField(blank=True, null=True, verbose_name='HOD comment')),
                ('coordinator_comment', models.TextField(blank=True, null=True)),
                ('prin_comment', models.TextField(blank=True, null=True, verbose_name='Vice Principal Comment')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('growth_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='observation', to='perf.growthplan')),
            ],
        ),
        migrations.CreateModel(
            name='SelfReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to='accounts.staff')),
            ],
        ),
        migrations.AddField(
            model_name='growthplan',
            name='reflection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='growth_plans', to='perf.selfreflection'),
        ),
        migrations.CreateModel(
            name='ReflectionDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('next_steps', models.TextField(blank=True, null=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perf.domain')),
                ('growths', models.ManyToManyField(blank=True, related_name='growth_reflections', to='perf.component')),
                ('strengths', models.ManyToManyField(blank=True, related_name='strength_reflections', to='perf.component')),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflection_domains', to='perf.selfreflection')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reflection', 'domain'), name='unique_reflection_domain')],
            },
        ),
    ]
